const products = [
  {
    name: "EchoVision Pro 6.7 5G Smart Phone",
    brand: "EchoVision",
    category: "Mobile",
    price: 449.99,
    stock: 90,
    image: "https://dummyimage.com/600x400/000/fff&text=EchoVision+Pro+Phone",
    description: "A powerful 5G smartphone with a 6.7-inch AMOLED display, dual-lens camera, and long-lasting battery.",
  },
  {
    name: "EchoVision Lite 5G",
    brand: "EchoVision",
    category: "Mobile",
    price: 329.99,
    stock: 120,
    image: "https://dummyimage.com/600x400/000/fff&text=EchoVision+Lite+Phone",
    description: "Affordable 5G performance, a bright display, and an all-day battery for everyday use.",
  },
  {
    name: "QuantumX Ultra 7 Pro",
    brand: "QuantumX",
    category: "Mobile",
    price: 999.99,
    stock: 40,
    image: "https://dummyimage.com/600x400/000/fff&text=QuantumX+Ultra+Phone",
    description: "Premium flagship phone with a 108MP camera, 12GB RAM, and 256GB storage.",
  },
  {
    name: "QuantumX Note 11",
    brand: "QuantumX",
    category: "Mobile",
    price: 579.99,
    stock: 68,
    image: "https://dummyimage.com/600x400/000/fff&text=QuantumX+Note+Phone",
    description: "Large-screen productivity phone with stylus support and fast charging.",
  },
  {
    name: "NovaCore Fold",
    brand: "NovaCore",
    category: "Mobile",
    price: 1399.99,
    stock: 18,
    image: "https://dummyimage.com/600x400/000/fff&text=NovaCore+Fold",
    description: "Premium foldable smartphone with a flexible AMOLED display and desktop-class performance.",
  },
  {
    name: "NovaCore Air",
    brand: "NovaCore",
    category: "Mobile",
    price: 699.99,
    stock: 82,
    image: "https://dummyimage.com/600x400/000/fff&text=NovaCore+Air",
    description: "Lightweight high-speed phone with professional camera features and AI enhancements.",
  },
  {
    name: "PixelMate 5G",
    brand: "PixelMate",
    category: "Mobile",
    price: 249.99,
    stock: 150,
    image: "https://dummyimage.com/600x400/000/fff&text=PixelMate+Phone",
    description: "Value-friendly 5G phone with a crisp display and upgraded camera mode.",
  },
  {
    name: "PixelMate Go",
    brand: "PixelMate",
    category: "Mobile",
    price: 199.99,
    stock: 160,
    image: "https://dummyimage.com/600x400/000/fff&text=PixelMate+Go",
    description: "Entry-level smartphone with reliable performance and battery life.",
  },
  {
    name: "Aurora Z9",
    brand: "Aurora",
    category: "Mobile",
    price: 549.99,
    stock: 76,
    image: "https://dummyimage.com/600x400/000/fff&text=Aurora+Z9",
    description: "Sleek phone with high refresh rate display and advanced night photography.",
  },
  {
    name: "Aurora Mini",
    brand: "Aurora",
    category: "Mobile",
    price: 279.99,
    stock: 132,
    image: "https://dummyimage.com/600x400/000/fff&text=Aurora+Mini",
    description: "Compact smartphone with long battery life and fast charging support.",
  },
  {
    name: "ZenBook Pro 14",
    brand: "Aether",
    category: "Laptop",
    price: 1299.99,
    stock: 35,
    image: "https://dummyimage.com/600x400/000/fff&text=ZenBook+Pro+14",
    description: "14-inch laptop with Intel i7, 16GB RAM, and a vivid OLED screen for creators.",
  },
  {
    name: "ZenBook Air 13",
    brand: "Aether",
    category: "Laptop",
    price: 999.99,
    stock: 54,
    image: "https://dummyimage.com/600x400/000/fff&text=ZenBook+Air+13",
    description: "Ultralight laptop with all-day battery life and a premium aluminum chassis.",
  },
  {
    name: "Gemini Pro 16",
    brand: "HyperTech",
    category: "Laptop",
    price: 1599.99,
    stock: 25,
    image: "https://dummyimage.com/600x400/000/fff&text=Gemini+Pro+16",
    description: "High-performance 16-inch laptop for gaming and content creation.",
  },
  {
    name: "Gemini Air 15",
    brand: "HyperTech",
    category: "Laptop",
    price: 1149.99,
    stock: 42,
    image: "https://dummyimage.com/600x400/000/fff&text=Gemini+Air+15",
    description: "Slim performance notebook with NVIDIA graphics and fast SSD storage.",
  },
  {
    name: "Stratus Chromebook",
    brand: "Stratus",
    category: "Laptop",
    price: 449.99,
    stock: 120,
    image: "https://dummyimage.com/600x400/000/fff&text=Stratus+Chromebook",
    description: "Budget-friendly Chromebook with lightweight design and long battery life.",
  },
  {
    name: "Stratus WorkPro",
    brand: "Stratus",
    category: "Laptop",
    price: 749.99,
    stock: 60,
    image: "https://dummyimage.com/600x400/000/fff&text=Stratus+WorkPro",
    description: "Reliable 14-inch work laptop with improved security and connectivity.",
  },
  {
    name: "VegaBook 17",
    brand: "Vega",
    category: "Laptop",
    price: 1099.99,
    stock: 33,
    image: "https://dummyimage.com/600x400/000/fff&text=VegaBook+17",
    description: "Large-screen productivity laptop optimized for spreadsheets and multitasking.",
  },
  {
    name: "VegaBook Studio",
    brand: "Vega",
    category: "Laptop",
    price: 1899.99,
    stock: 14,
    image: "https://dummyimage.com/600x400/000/fff&text=VegaBook+Studio",
    description: "Creator-focused notebook with color-accurate display and premium graphics.",
  },
  {
    name: "Pulse X1 Smartwatch",
    brand: "Pulse",
    category: "Smartwatch",
    price: 229.99,
    stock: 105,
    image: "https://dummyimage.com/600x400/000/fff&text=Pulse+X1",
    description: "Fitness smartwatch with heart-rate monitoring, GPS, and music controls.",
  },
  {
    name: "Pulse Fit 2",
    brand: "Pulse",
    category: "Smartwatch",
    price: 149.99,
    stock: 145,
    image: "https://dummyimage.com/600x400/000/fff&text=Pulse+Fit+2",
    description: "Affordable smartwatch with sleep tracking and 7-day battery life.",
  },
  {
    name: "Orbit Elite Watch",
    brand: "Orbit",
    category: "Smartwatch",
    price: 319.99,
    stock: 68,
    image: "https://dummyimage.com/600x400/000/fff&text=Orbit+Elite",
    description: "Premium smartwatch with stainless steel case, LTE support, and advanced health metrics.",
  },
  {
    name: "Orbit Classic",
    brand: "Orbit",
    category: "Smartwatch",
    price: 179.99,
    stock: 96,
    image: "https://dummyimage.com/600x400/000/fff&text=Orbit+Classic",
    description: "Everyday smartwatch featuring reliable notifications and workout tracking.",
  },
  {
    name: "ZenWatch Neo",
    brand: "ZenWatch",
    category: "Smartwatch",
    price: 199.99,
    stock: 88,
    image: "https://dummyimage.com/600x400/000/fff&text=ZenWatch+Neo",
    description: "Balanced smartwatch with health tracking, mobile payments, and sleek design.",
  },
  {
    name: "ZenWatch Active",
    brand: "ZenWatch",
    category: "Smartwatch",
    price: 259.99,
    stock: 74,
    image: "https://dummyimage.com/600x400/000/fff&text=ZenWatch+Active",
    description: "Sport watch with rugged build, GPS routes, and VO2 max tracking.",
  },
  {
    name: "Beam Buds Pro",
    brand: "Beam",
    category: "Earbuds",
    price: 129.99,
    stock: 140,
    image: "https://dummyimage.com/600x400/000/fff&text=Beam+Buds+Pro",
    description: "Noise-cancelling true wireless earbuds with 24-hour total battery life.",
  },
  {
    name: "Beam Buds Lite",
    brand: "Beam",
    category: "Earbuds",
    price: 69.99,
    stock: 170,
    image: "https://dummyimage.com/600x400/000/fff&text=Beam+Buds+Lite",
    description: "Comfortable earbuds with clear sound, lots of playtime, and touch controls.",
  },
  {
    name: "SkyTone AirPods",
    brand: "SkyTone",
    category: "Earbuds",
    price: 179.99,
    stock: 95,
    image: "https://dummyimage.com/600x400/000/fff&text=SkyTone+AirPods",
    description: "Sleek wireless earbuds with adaptive EQ and spatial audio support.",
  },
  {
    name: "SkyTone Studio",
    brand: "SkyTone",
    category: "Earbuds",
    price: 229.99,
    stock: 72,
    image: "https://dummyimage.com/600x400/000/fff&text=SkyTone+Studio",
    description: "Studio-quality wireless earbuds with superior bass and active noise cancellation.",
  },
  {
    name: "BassWave TWS",
    brand: "BassWave",
    category: "Earbuds",
    price: 89.99,
    stock: 152,
    image: "https://dummyimage.com/600x400/000/fff&text=BassWave+TWS",
    description: "Affordable true wireless earbuds with strong bass and stable Bluetooth.",
  },
  {
    name: "BassWave Pro ANC",
    brand: "BassWave",
    category: "Earbuds",
    price: 139.99,
    stock: 118,
    image: "https://dummyimage.com/600x400/000/fff&text=BassWave+Pro+ANC",
    description: "Premium ANC earbuds with rich sound and a compact charging case.",
  },
  {
    name: "NovaSound Bar 2",
    brand: "NovaSound",
    category: "Audio",
    price: 249.99,
    stock: 45,
    image: "https://dummyimage.com/600x400/000/fff&text=NovaSound+Bar",
    description: "Soundbar with Dolby Atmos support and wireless subwoofer compatibility.",
  },
  {
    name: "NovaSound Mini Speaker",
    brand: "NovaSound",
    category: "Audio",
    price: 79.99,
    stock: 120,
    image: "https://dummyimage.com/600x400/000/fff&text=NovaSound+Mini",
    description: "Portable Bluetooth speaker with rich sound and 12-hour battery life.",
  },
  {
    name: "HyperDrive USB-C Hub",
    brand: "HyperDrive",
    category: "Accessory",
    price: 49.99,
    stock: 220,
    image: "https://dummyimage.com/600x400/000/fff&text=HyperDrive+Hub",
    description: "Multiport USB-C hub with HDMI, Ethernet, SD card reader, and pass-through charging.",
  },
  {
    name: "HyperDrive Wireless Mouse",
    brand: "HyperDrive",
    category: "Accessory",
    price: 39.99,
    stock: 180,
    image: "https://dummyimage.com/600x400/000/fff&text=HyperDrive+Mouse",
    description: "Ergonomic wireless mouse with adjustable DPI and long battery life.",
  },
  {
    name: "PixelView 27 4K Monitor",
    brand: "PixelView",
    category: "Monitor",
    price: 299.99,
    stock: 38,
    image: "https://dummyimage.com/600x400/000/fff&text=PixelView+4K+Monitor",
    description: "27-inch 4K monitor with HDR support and slim bezels.",
  },
  {
    name: "PixelView 24 IPS Monitor",
    brand: "PixelView",
    category: "Monitor",
    price: 189.99,
    stock: 47,
    image: "https://dummyimage.com/600x400/000/fff&text=PixelView+24+Monitor",
    description: "24-inch IPS display with vivid color accuracy and fast refresh.",
  },
  {
    name: "VisionCam Pro",
    brand: "VisionCam",
    category: "Camera",
    price: 549.99,
    stock: 29,
    image: "https://dummyimage.com/600x400/000/fff&text=VisionCam+Pro",
    description: "Mirrorless camera with 4K capture, interchangeable lenses, and built-in stabilization.",
  },
  {
    name: "VisionCam Pocket",
    brand: "VisionCam",
    category: "Camera",
    price: 349.99,
    stock: 55,
    image: "https://dummyimage.com/600x400/000/fff&text=VisionCam+Pocket",
    description: "Compact travel camera with 20MP sensor and easy wireless sharing.",
  },
  {
    name: "SmartTab 11",
    brand: "SmartTab",
    category: "Tablet",
    price: 329.99,
    stock: 84,
    image: "https://dummyimage.com/600x400/000/fff&text=SmartTab+11",
    description: "11-inch tablet with pencil support and productivity apps.",
  },
  {
    name: "SmartTab Fold",
    brand: "SmartTab",
    category: "Tablet",
    price: 599.99,
    stock: 26,
    image: "https://dummyimage.com/600x400/000/fff&text=SmartTab+Fold",
    description: "Foldable tablet with multitasking display and stylus-ready interface.",
  },
  {
    name: "PowerCore 100W Charger",
    brand: "PowerCore",
    category: "Accessory",
    price: 39.99,
    stock: 190,
    image: "https://dummyimage.com/600x400/000/fff&text=PowerCore+Charger",
    description: "Compact 100W USB-C charger for laptops, tablets, and phones.",
  },
  {
    name: "PowerCore Wireless Pad",
    brand: "PowerCore",
    category: "Accessory",
    price: 24.99,
    stock: 170,
    image: "https://dummyimage.com/600x400/000/fff&text=PowerCore+Pad",
    description: "Wireless charging pad with fast charging support for compatible devices.",
  },
  {
    name: "Aurora Smartbuds",
    brand: "Aurora",
    category: "Earbuds",
    price: 159.99,
    stock: 101,
    image: "https://dummyimage.com/600x400/000/fff&text=Aurora+Smartbuds",
    description: "Smart earbuds with voice assistant integration and adaptive noise control.",
  },
  {
    name: "Aurora SoundFit",
    brand: "Aurora",
    category: "Earbuds",
    price: 119.99,
    stock: 112,
    image: "https://dummyimage.com/600x400/000/fff&text=Aurora+SoundFit",
    description: "Sport earbuds designed for secure fit and sweat resistance.",
  },
];

module.exports = { products };
